export const constantes = {
  provincias:
    [
      "Álava/Araba",
      "Albacete",
      "Alicante",
      "Almería",
      "Asturias",
      "Ávila",
      "Badajoz",
      "Baleares",
      "Barcelona",
      "Burgos",
      "Cáceres",
      "Cádiz",
      "Cantabria",
      "Castellón",
      "Ceuta",
      "Ciudad Real",
      "Córdoba",
      "Cuenca",
      "Gerona/Girona",
      "Granada",
      "Guadalajara",
      "Guipúzcoa/Gipuzkoa",
      "Huelva",
      "Huesca",
      "Jaén",
      "La Coruña/A Coruña",
      "La Rioja",
      "Las Palmas",
      "León",
      "Lérida/Lleida",
      "Lugo",
      "Madrid",
      "Málaga",
      "Melilla",
      "Murcia",
      "Navarra",
      "Orense/Ourense",
      "Palencia",
      "Pontevedra",
      "Salamanca",
      "Segovia",
      "Sevilla",
      "Soria",
      "Tarragona",
      "Tenerife",
      "Teruel",
      "Toledo",
      "Valencia",
      "Valladolid",
      "Vizcaya/Bizkaia",
      "Zamora",
      "Zaragoza"
    ],
    documentos: [
      "Carta",
      "Informe Policial",
      "Informe Forense",
      "Declaración de Testigo",
      "Certificado de Antecedentes",
      "Orden Judicial",
      "Registro de Propiedad",
      "Expediente Penal",
      "Permiso de Residencia",
      "Memorando Interno",
      "Parte de Accidente",
      "Autorización Expresa",
      "Documento de Identidad",
      "Carnet de Conducir",
      "Pasaporte",
      "Otros"
    ],
    idiomas: [
      "Alemán",
      "Árabe",
      "Bengalí",
      "Birmano",
      "Bhojpuri",
      "Chino mandarín",
      "Coreano",
      "Español",
      "Francés",
      "Gujarati",
      "Hindi",
      "Indonesio",
      "Inglés",
      "Italiano",
      "Japonés",
      "Javanés",
      "Kannada",
      "Khmer",
      "Malayalam",
      "Marathi",
      "Neerlandés",
      "Oriya",
      "Pastún",
      "Persa",
      "Polaco",
      "Portugués",
      "Punjabi",
      "Rumano",
      "Ruso",
      "Serbio",
      "Sundanés",
      "Swahili",
      "Tamil",
      "Telugu",
      "Thai",
      "Turco",
      "Ucraniano",
      "Urdu",
      "Vietnamita",
      "Wu (shanghainés)",
    ]
  }

